name: fedros
on: 
  push:
    branches:
      - main

jobs:
  test:  
    runs-on: ubuntu-latest
  
    steps: 
      - name: Echo
        run: echo devops 


  test2:
    runs-on: ubuntu-latest
    needs: test
      
    steps:
      - name: Echo2
        run: echo Devaps Example

